import { DatabaseService } from '../utils/database'
import {
  InternalLink,
  Article,
  Tag,
  InternalLinkSettings,
  SEOConfig,
  RelatedArticlesParams
} from '../models/types'

interface LinkOpportunity {
  keyword: string
  targetType: 'article' | 'tag'
  targetId: string
  targetSlug: string
  targetTitle: string
  relevanceScore: number
  position: number
  context: string
}

interface ProcessedContent {
  content: string
  addedLinks: InternalLink[]
}

export class InternalLinkService {
  constructor(private db: DatabaseService) {}

  // Process article content and add internal links
  async processArticleLinks(
    articleId: string,
    content: string,
    seoConfig?: SEOConfig
  ): Promise<ProcessedContent> {
    const settings = seoConfig?.internal_link_settings || this.getDefaultSettings()

    if (!settings.enabled) {
      return { content, addedLinks: [] }
    }

    const article = await this.db.executeOne<Article>(
      'SELECT * FROM articles WHERE id = ?',
      [articleId]
    )

    if (!article) {
      throw new Error('Article not found')
    }

    // Remove existing auto-generated links for this article
    await this.removeAutoGeneratedLinks(articleId)

    // Find link opportunities
    const opportunities = await this.findLinkOpportunities(
      article.site_id,
      content,
      articleId,
      settings
    )

    // Filter and sort opportunities
    const selectedOpportunities = this.selectBestOpportunities(
      opportunities,
      settings
    )

    // Apply links to content
    const result = this.applyLinksToContent(
      content,
      selectedOpportunities,
      settings
    )

    // Save links to database
    const addedLinks: InternalLink[] = []
    for (const opportunity of selectedOpportunities) {
      const link = await this.saveInternalLink(
        article.site_id,
        articleId,
        opportunity
      )
      addedLinks.push(link)
    }

    return {
      content: result,
      addedLinks
    }
  }

  // Find potential link opportunities in content
  private async findLinkOpportunities(
    siteId: string,
    content: string,
    excludeArticleId: string,
    settings: InternalLinkSettings
  ): Promise<LinkOpportunity[]> {
    const opportunities: LinkOpportunity[] = []

    // Get potential target articles
    if (settings.link_to_related_articles) {
      const articles = await this.db.execute<Article>(
        `SELECT * FROM articles
         WHERE site_id = ? AND id != ? AND status = 'published'
         ORDER BY view_count DESC, created_at DESC`,
        [siteId, excludeArticleId]
      )

      for (const article of articles) {
        const articleOpportunities = this.findKeywordMatches(
          content,
          article.title,
          'article',
          article.id,
          article.slug,
          article.title,
          settings
        )
        opportunities.push(...articleOpportunities)

        // Also check meta keywords if available
        if (article.meta_keywords) {
          const keywords = article.meta_keywords.split(',').map(k => k.trim())
          for (const keyword of keywords) {
            if (keyword.length >= settings.minimum_keyword_length) {
              const keywordOpportunities = this.findKeywordMatches(
                content,
                keyword,
                'article',
                article.id,
                article.slug,
                article.title,
                settings
              )
              opportunities.push(...keywordOpportunities)
            }
          }
        }
      }
    }

    // Get potential target tags
    if (settings.link_to_tags) {
      const tags = await this.db.execute<Tag>(
        `SELECT t.*, COUNT(at.article_id) as article_count
         FROM tags t
         LEFT JOIN article_tags at ON t.id = at.tag_id
         WHERE t.site_id = ?
         GROUP BY t.id
         HAVING article_count > 0
         ORDER BY article_count DESC`,
        [siteId]
      )

      for (const tag of tags) {
        const tagOpportunities = this.findKeywordMatches(
          content,
          tag.name,
          'tag',
          tag.id,
          tag.slug,
          tag.name,
          settings
        )
        opportunities.push(...tagOpportunities)
      }
    }

    return opportunities
  }

  // Find keyword matches in content
  private findKeywordMatches(
    content: string,
    keyword: string,
    targetType: 'article' | 'tag',
    targetId: string,
    targetSlug: string,
    targetTitle: string,
    settings: InternalLinkSettings
  ): LinkOpportunity[] {
    const opportunities: LinkOpportunity[] = []

    if (keyword.length < settings.minimum_keyword_length) {
      return opportunities
    }

    // Skip if keyword is in exclude list
    if (settings.exclude_words?.some(word =>
      keyword.toLowerCase().includes(word.toLowerCase())
    )) {
      return opportunities
    }

    // Remove HTML tags for text analysis
    const plainText = content.replace(/<[^>]*>/g, ' ')
    const words = plainText.split(/\s+/)

    // Find exact and partial matches
    const keywordLower = keyword.toLowerCase()
    const keywordRegex = new RegExp(`\\b${this.escapeRegex(keyword)}\\b`, 'gi')

    let match
    let position = 0

    while ((match = keywordRegex.exec(content)) !== null) {
      // Check if this position is already within an existing link
      if (this.isWithinExistingLink(content, match.index)) {
        continue
      }

      // Get context around the match
      const contextStart = Math.max(0, match.index - 100)
      const contextEnd = Math.min(content.length, match.index + keyword.length + 100)
      const context = content.substring(contextStart, contextEnd)

      // Calculate relevance score
      const relevanceScore = this.calculateRelevanceScore(
        keyword,
        context,
        targetType,
        position
      )

      opportunities.push({
        keyword: match[0], // Preserve original case
        targetType,
        targetId,
        targetSlug,
        targetTitle,
        relevanceScore,
        position: match.index,
        context: context.replace(/<[^>]*>/g, ' ').trim()
      })

      position++
    }

    return opportunities
  }

  // Select best link opportunities based on settings
  private selectBestOpportunities(
    opportunities: LinkOpportunity[],
    settings: InternalLinkSettings
  ): LinkOpportunity[] {
    // Sort by relevance score
    opportunities.sort((a, b) => b.relevanceScore - a.relevanceScore)

    const selected: LinkOpportunity[] = []
    const usedKeywords = new Set<string>()
    const usedTargets = new Set<string>()

    for (const opportunity of opportunities) {
      // Respect max links limit
      if (selected.length >= settings.max_links_per_article) {
        break
      }

      // Only link once per article if setting is enabled
      if (settings.only_link_once_per_article) {
        const keywordKey = opportunity.keyword.toLowerCase()
        if (usedKeywords.has(keywordKey)) {
          continue
        }
        usedKeywords.add(keywordKey)
      }

      // Don't link to the same target multiple times
      if (usedTargets.has(opportunity.targetId)) {
        continue
      }
      usedTargets.add(opportunity.targetId)

      selected.push(opportunity)
    }

    return selected
  }

  // Apply links to content
  private applyLinksToContent(
    content: string,
    opportunities: LinkOpportunity[],
    settings: InternalLinkSettings
  ): string {
    // Sort opportunities by position (descending) to avoid index shifts
    opportunities.sort((a, b) => b.position - a.position)

    let processedContent = content

    for (const opportunity of opportunities) {
      const linkUrl = opportunity.targetType === 'article'
        ? `/articles/${opportunity.targetSlug}`
        : `/tags/${opportunity.targetSlug}`

      const linkClass = settings.link_class ? ` class="${settings.link_class}"` : ''
      const linkHtml = `<a href="${linkUrl}"${linkClass} title="${this.escapeHtml(opportunity.targetTitle)}">${opportunity.keyword}</a>`

      // Find the exact position in the current content (might have shifted)
      const beforePart = processedContent.substring(0, opportunity.position)
      const afterPart = processedContent.substring(opportunity.position + opportunity.keyword.length)

      processedContent = beforePart + linkHtml + afterPart
    }

    return processedContent
  }

  // Calculate relevance score for a link opportunity
  private calculateRelevanceScore(
    keyword: string,
    context: string,
    targetType: 'article' | 'tag',
    position: number
  ): number {
    let score = 0

    // Base score for keyword length
    score += keyword.length * 2

    // Bonus for exact case match
    if (context.includes(keyword)) {
      score += 10
    }

    // Bonus for being in heading context
    if (context.includes('<h') || context.includes('</h')) {
      score += 15
    }

    // Bonus for being early in content
    if (position === 0) {
      score += 20
    } else if (position < 3) {
      score += 10
    }

    // Type-based scoring
    if (targetType === 'article') {
      score += 5 // Slight preference for articles over tags
    }

    return score
  }

  // Save internal link to database
  private async saveInternalLink(
    siteId: string,
    fromArticleId: string,
    opportunity: LinkOpportunity
  ): Promise<InternalLink> {
    const id = this.db.generateId()
    const now = new Date().toISOString()

    const link: Omit<InternalLink, 'click_count'> = {
      id,
      site_id: siteId,
      from_article_id: fromArticleId,
      anchor_text: opportunity.keyword,
      context: opportunity.context,
      position: opportunity.position,
      created_at: now
    }

    if (opportunity.targetType === 'article') {
      link.to_article_id = opportunity.targetId
    } else {
      link.to_tag_id = opportunity.targetId
    }

    await this.db.executeRun(
      `INSERT INTO internal_links (
        id, site_id, from_article_id, to_article_id, to_tag_id, to_url,
        anchor_text, context, position, created_at, click_count
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        siteId,
        fromArticleId,
        link.to_article_id || null,
        link.to_tag_id || null,
        link.to_url || null,
        link.anchor_text,
        link.context,
        link.position,
        now,
        0
      ]
    )

    return { ...link, click_count: 0 }
  }

  // Remove auto-generated links for an article
  private async removeAutoGeneratedLinks(articleId: string): Promise<void> {
    await this.db.executeRun(
      'DELETE FROM internal_links WHERE from_article_id = ?',
      [articleId]
    )
  }

  // Get internal links analytics
  async getInternalLinksAnalytics(siteId: string): Promise<{
    totalLinks: number
    topSourceArticles: { title: string; slug: string; linkCount: number }[]
    topTargetArticles: { title: string; slug: string; linkCount: number }[]
    topTargetTags: { name: string; slug: string; linkCount: number }[]
    clickThroughRates: { anchorText: string; clicks: number; impressions: number }[]
  }> {
    // Total links count
    const totalResult = await this.db.executeOne<{ count: number }>(
      'SELECT COUNT(*) as count FROM internal_links WHERE site_id = ?',
      [siteId]
    )
    const totalLinks = totalResult?.count || 0

    // Top source articles
    const topSourceArticles = await this.db.execute<{ title: string; slug: string; linkCount: number }>(
      `SELECT a.title, a.slug, COUNT(il.id) as linkCount
       FROM articles a
       INNER JOIN internal_links il ON a.id = il.from_article_id
       WHERE a.site_id = ?
       GROUP BY a.id
       ORDER BY linkCount DESC
       LIMIT 10`,
      [siteId]
    )

    // Top target articles
    const topTargetArticles = await this.db.execute<{ title: string; slug: string; linkCount: number }>(
      `SELECT a.title, a.slug, COUNT(il.id) as linkCount
       FROM articles a
       INNER JOIN internal_links il ON a.id = il.to_article_id
       WHERE a.site_id = ?
       GROUP BY a.id
       ORDER BY linkCount DESC
       LIMIT 10`,
      [siteId]
    )

    // Top target tags
    const topTargetTags = await this.db.execute<{ name: string; slug: string; linkCount: number }>(
      `SELECT t.name, t.slug, COUNT(il.id) as linkCount
       FROM tags t
       INNER JOIN internal_links il ON t.id = il.to_tag_id
       WHERE t.site_id = ?
       GROUP BY t.id
       ORDER BY linkCount DESC
       LIMIT 10`,
      [siteId]
    )

    // Click-through rates (simplified - would need impression tracking)
    const clickThroughRates = await this.db.execute<{ anchorText: string; clicks: number; impressions: number }>(
      `SELECT anchor_text as anchorText, SUM(click_count) as clicks, COUNT(*) as impressions
       FROM internal_links
       WHERE site_id = ?
       GROUP BY anchor_text
       ORDER BY clicks DESC
       LIMIT 20`,
      [siteId]
    )

    return {
      totalLinks,
      topSourceArticles,
      topTargetArticles,
      topTargetTags,
      clickThroughRates
    }
  }

  // Track link clicks
  async trackLinkClick(linkId: string): Promise<void> {
    await this.db.executeRun(
      'UPDATE internal_links SET click_count = click_count + 1 WHERE id = ?',
      [linkId]
    )
  }

  // Get internal links for an article
  async getArticleInternalLinks(articleId: string): Promise<InternalLink[]> {
    return this.db.execute<InternalLink>(
      'SELECT * FROM internal_links WHERE from_article_id = ? ORDER BY position ASC',
      [articleId]
    )
  }

  // Get backlinks to an article
  async getArticleBacklinks(articleId: string): Promise<InternalLink[]> {
    return this.db.execute<InternalLink>(
      'SELECT * FROM internal_links WHERE to_article_id = ? ORDER BY created_at DESC',
      [articleId]
    )
  }

  // Get backlinks to a tag
  async getTagBacklinks(tagId: string): Promise<InternalLink[]> {
    return this.db.execute<InternalLink>(
      'SELECT * FROM internal_links WHERE to_tag_id = ? ORDER BY created_at DESC',
      [tagId]
    )
  }

  // Find related articles based on internal links
  async findRelatedArticles(
    articleId: string,
    params: RelatedArticlesParams = {}
  ): Promise<Article[]> {
    const limit = params.limit || 5

    // Find articles linked from this article
    const linkedArticles = await this.db.execute<Article>(
      `SELECT DISTINCT a.*
       FROM articles a
       INNER JOIN internal_links il ON a.id = il.to_article_id
       WHERE il.from_article_id = ? AND a.status = 'published'
       ORDER BY il.click_count DESC, a.view_count DESC
       LIMIT ?`,
      [articleId, Math.ceil(limit / 2)]
    )

    // Find articles linking to this article
    const linkingArticles = await this.db.execute<Article>(
      `SELECT DISTINCT a.*
       FROM articles a
       INNER JOIN internal_links il ON a.id = il.from_article_id
       WHERE il.to_article_id = ? AND a.status = 'published'
       ORDER BY il.click_count DESC, a.view_count DESC
       LIMIT ?`,
      [articleId, Math.ceil(limit / 2)]
    )

    // Combine and deduplicate
    const allRelated = [...linkedArticles, ...linkingArticles]
    const unique = allRelated.filter((article, index, self) =>
      index === self.findIndex(a => a.id === article.id) &&
      article.id !== params.excludeId
    )

    return unique.slice(0, limit)
  }

  // Generate breadcrumb navigation
  generateBreadcrumbs(
    currentPath: string,
    site: { name: string; domain: string },
    article?: Article,
    tag?: Tag
  ): Array<{ name: string; url: string }> {
    const breadcrumbs = [
      { name: site.name, url: '/' }
    ]

    if (article) {
      breadcrumbs.push(
        { name: 'Articles', url: '/articles' },
        { name: article.title, url: `/articles/${article.slug}` }
      )
    } else if (tag) {
      breadcrumbs.push(
        { name: 'Tags', url: '/tags' },
        { name: tag.name, url: `/tags/${tag.slug}` }
      )
    } else if (currentPath.startsWith('/articles')) {
      breadcrumbs.push({ name: 'Articles', url: '/articles' })
    } else if (currentPath.startsWith('/tags')) {
      breadcrumbs.push({ name: 'Tags', url: '/tags' })
    }

    return breadcrumbs
  }

  // Utility methods

  private getDefaultSettings(): InternalLinkSettings {
    return {
      enabled: true,
      max_links_per_article: 5,
      link_to_related_articles: true,
      link_to_tags: true,
      minimum_keyword_length: 3,
      only_link_once_per_article: true,
      link_class: 'internal-link',
      exclude_words: ['the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by']
    }
  }

  private isWithinExistingLink(content: string, position: number): boolean {
    // Find the nearest opening and closing <a> tags
    const beforeContent = content.substring(0, position)
    const afterContent = content.substring(position)

    const lastOpenTag = beforeContent.lastIndexOf('<a ')
    const lastCloseTag = beforeContent.lastIndexOf('</a>')
    const nextCloseTag = afterContent.indexOf('</a>')

    // If we're between an opening tag and its closing tag
    return lastOpenTag > lastCloseTag && nextCloseTag !== -1
  }

  private escapeRegex(string: string): string {
    return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')
  }
}